version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot
    restart: unless-stopped
    depends_on:
      - memcached
    ports:
      - "5000:5000"
    environment:
      - RATELIMIT_STORAGE_URI=memcached://memcached:11211
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      - ./google-credentials.json:/app/google-credentials.json:ro
      - app-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  memcached:
    image: memcached:1.6-alpine
    container_name: qb-autogen-memcached-prod
    restart: unless-stopped

volumes:
  app-logs:
    driver: local
